# Generated by Django 4.1 on 2022-08-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=50)),
                ('aname', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=50)),
                ('pyear', models.CharField(max_length=50)),
            ],
        ),
    ]
